[build]
# The index HTML file to drive the bundling process.
target = "index.html"

# Build in release mode.
release = true

# The output dir for all final assets.
dist = "dist"

# The public URL from which assets are served.
public_url = "/alexismayer.github.io/"

# Tailwind CSS configuration
tailwind-input-file = "style/tailwind.css"

[watch]
# Paths to watch for changes.
watch = ["src", "Cargo.toml", "index.html", "style"]

[serve]
# The addresses to serve on.
addresses = ["127.0.0.1"]

# The port to serve on.
port = 8080

# Open a browser tab once the initial build is complete.
open = true

[clean]
# Additional paths to clean.
cargo = true
